### ISSUE TITLE
Question: Using "Name" variable to send SMS for subscribers list

### ISSUE THREAD

**Issue by starnetwork** [veronalabs/wp-sms#13]
Hi,
in Send SMS page, how can I insert the "Name" variable to send more "Personal" message to the list?

Regards,

**Comment by mostafasoufi** [comment]
Hi @starnetwork,

You can use a `foreach` to sending sms. But it not recomended, Because you must send a request to gateway for each number.

**Comment by starnetwork** [comment]
Thanks Mostafa,
we talking about 30-50 Subscribers
so it's not heavy to the Gateway even if we sending foreach
but I didn't see this functionality

the best way is if possible to add the "Name" variable to the Text area as part of the message and add note in the bottom that
* Sending with "Name" variable will send this for each as separated request to the gateway.

Possible?

![snip_20170816120037](https://user-images.githubusercontent.com/626945/29355675-9d441884-827a-11e7-93ad-4bfcb04faee0.png)

**Comment by mostafasoufi** [comment]
It's possible. but we can't adding this feature in the plugin with publicly.

**Comment by starnetwork** [comment]
wow, thanks!
it's possible to add this as additional function can be turned Nn / Off to the Pro package?

**Comment by mostafasoufi** [comment]
Your welcome. This feature affect in two section (Send SMS page and Current gateway class)
So you can only add a customization version.

**Comment by starnetwork** [comment]
Hi,
no possible to add some:
if function exists
and on this way it's will add the option only if the gateway class updated with this support?

on this way we can add support in another provider over the time, no?

**Comment by mostafasoufi** [comment]
It's possible. but need to add this feature to all gateways and takes up a lot of time.

**Comment by starnetwork** [comment]
I mean, add this functionality to the Send SMS page, and this will check if function exists
for the currently usage Gateway
if this supported, it's will show the option, if no, it's will continue to work as it's now.

so on this way possible to add this only to some of gateway and it's can be During time and on demand, and not need to do it to all the gateways from the beginning...

All the best,

**Comment by mostafasoufi** [comment]
Yes, Unfortunately, a few gateways supported this capability. But it's a good way.

**Comment by starnetwork** [comment]
so, possible to add this support on next release?

**Comment by mostafasoufi** [comment]
It's possible. but I'm not sure for next release.

**Comment by starnetwork** [comment]
Thanks!
we will follow the release notes...

**Comment by starnetwork** [comment]
Hi,
possible to give priority to that issue please?

**Comment by starnetwork** [comment]
Hi @mostafasoufi 
what Help wanted mean?
estimate for that?

**Comment by mostafasoufi** [comment]
Here is an example of sending SMS supported subscriber name.
```
foreach ( $this->to as $to ) {
	// Get subscriber.
	$subscriber   = $this->db->get_row( $this->db->prepare( "SELECT * from `{$this->tb_prefix}sms_subscribes` WHERE mobile =%s;", $to ) );

	// Build SMS text.
	$template_vars = array(
		'%name%' => $subscriber->name,
	);
	$message       = str_replace( array_keys( $template_vars ), array_values( $template_vars ), $this->msg );

	// Send SMS function. you should change sendsms method instead of your current gateway.
	$result = sendsms( $to, $message );
}
```
use above code in your gateway class into `SendSMS` method.
