### ISSUE TITLE
Need shortcodes for plugin. 

### ISSUE THREAD

**Issue by Xayaan** [veronalabs/wp-sms#14]
Actions and filters is great, but what about shortcodes for normal users?

**Comment by mostafasoufi** [comment]
Hi @Xayaan,

Shortcode for what? Please explain more about this shortcodes.

**Comment by Xayaan** [comment]
shortcodes like [mobile-number]. Better user experience. 

Also, i have a problem with a existing site, im using wp sms and wp sms pro i purchased from codecanyon, 

It's not going to verify field after register, try it here : https://dhibazaar.com/my-account/ 

Use the phone number : +960 7772930 (as currently, i've allowed only Maldives as country for SMS in twilio) 

Thank you!

**Comment by mostafasoufi** [comment]
> shortcodes like [mobile-number]. Better user experience.

`[mobile-number]` In the send SMS page? Or WordPress contents?

And about your question, Please Go to help.veronalabs.com to get support of Pro pack version.

**Comment by Xayaan** [comment]
In Wordpress contents or either in a PHP using `<?php echo do_shortcode("[shortcode]"); ?>`

Okay, thanks! :)

**Comment by mostafasoufi** [comment]
I don't know about this short code: `[mobile-number]` what does it do.
Can you send a list with full description about the shortcodes?

**Comment by MHitMaN** [comment]
Added Shortcode and check all conditions too with form actions, all working without any error or problem.
To use Shortcode must be like this :
```
[wp-sms-subscriber-form]
```

**Comment by mostafasoufi** [comment]
Thank you 👍
