### ISSUE TITLE
Settings  - checkboxes

### ISSUE THREAD

**Issue by toddsantoro** [veronalabs/wp-sms#141]
PHP 8+
WP 6.0

The checkbox settings, once checked, can't be unchecked on the general settings page.

**Comment by mostafasoufi** [comment]
Hi,

Thank you for opening the issue, if you're talking about the **"Add Mobile number field"** this is enables automatically again once the `mobile_verify` is enabled.

**wp-content/plugins/wp-sms-pro/includes/integrations/class-wpsms-pro-wordpress.php:L37**

```
if (isset($this->options['mobile_verify'])) {
    $wpsms_option = Option::getOptions();
    if (empty($wpsms_option['add_mobile_field'])) {
        // Enable mobile field option
        $wpsms_option['add_mobile_field'] = 1;

        // Update entire array
        update_option('wpsms_settings', $wpsms_option);
    }

  ...
```

**Comment by toddsantoro** [comment]
M,

All the check boxes on the general tab, once checked, will not let me uncheck them. Let me disable all plugins and switch to the 2022 theme and check again. I thought I did this befor opening the issue. Standby. 

Cheers,

Todd Santoro
Sr. Software Engineer
ToddSantoro.com Designs

tel :: 305.699.3515
sms :: 305.699.3515
email :: ***@***.***
web :: toddsantoro.com
skype :: toddsantoro007
rss :: toddsantoro.com/feed
twitter :: @toddsantoro

sent from my mobile command center.
