### ISSUE TITLE
Gateway iransmspanel 

### ISSUE THREAD

**Issue by netusir** [veronalabs/wp-sms#15]
Hi
This plugin Problem with iransmspanel  Gateway
Please Fix It.
 Fatal error: Call to undefined method iransmspanel::SendSMS() in /home/public_html/wp-content/plugins/wp-sms/wp-sms.php on line 391
Thanks.

**Comment by mostafasoufi** [comment]
Hi @netusir,

Fixed in this https://github.com/veronalabs/wp-sms/commit/e081157952f2e91185a1a933b269cace5848dbc8 commit.
