### ISSUE TITLE
Adding new gateway - MSG360.IN

### ISSUE THREAD

**Issue by karanzip** [veronalabs/wp-sms#17]
[msg360.class.zip](https://github.com/veronalabs/wp-sms/files/1481376/msg360.class.zip)

Request you to add the above gateway in the plugin for further updates. 

If you require any further credentials feel free to let me know. Thank you.

**Comment by mostafasoufi** [comment]
Hi @karanzip,

Please send your gateway through Pull request in this repo.
See this article:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
