### ISSUE TITLE
SMS Gateway say Deactive

### ISSUE THREAD

**Issue by trainyoucon** [veronalabs/wp-sms#2]
Hi there.

Purchased the Pro-plugin, installed but do not seem to get any response from your helpdesk, reference: [#910930]

On the SMS-Gateway, we selected the provider "Bulksms.com", but the status below say "Deactive".

We double checked that all the login details required is correct, also tried different formats

**Comment by mostafasoufi** [comment]
Hello,
Here is not good place to ask questions. please go to help.veronalabs.com

**Comment by trainyoucon** [comment]
Hi there.

 

I did, but I’m not getting any response.

 

Ezra Steenkamp

**Comment by mostafasoufi** [comment]
Please wait to get support on help.veronalabs.com
