### ISSUE TITLE
Please Add Trumpia As Additonal SMS Gateway

### ISSUE THREAD

**Issue by SooBahkDo** [veronalabs/wp-sms#24]
Please Add Trumpia As Additonal SMS Gateway

SMS
https://trumpia.com/

API DOCUMENTATION
https://trumpia.com/api/overview.php 

FIVE MINUTE DEMO VIDEO
https://trumpia.com/5-min-demo.php

FREE DEVELOPER TEST ACCOUNT
https://trumpia.com/main/contactus.php?type=Free%20API%20Test%20Account

Thanks for considering this request.

Phil D

**Comment by mostafasoufi** [comment]
Should be added by yourself and approved with merge request.

Otherwise, we can add to Pro Pack version.

**Comment by SooBahkDo** [comment]
Hello,
I am not a developer so adding to the Pro Pack seems reasonable.
Trumpia is a popular SMS service and adding it may help increase Pro pack sales.
Thanks,
Phil D
