### ISSUE TITLE
Cannot change sender ID/Number

### ISSUE THREAD

**Issue by doctorfox** [veronalabs/wp-sms#27]
On the send SMS page there is a label for "Send from:"
But there is no text input field to enter the sender.
![image](https://user-images.githubusercontent.com/183775/41856876-0b1c6d66-788e-11e8-96a5-dfeec096aea5.png)

**Comment by mostafasoufi** [comment]
The sender ID/Number can be changed in the Setting page -> Gateway

**Comment by doctorfox** [comment]
Please this is a valid problem.
When sending SMS using other plugins there is a configuration/settings page where you set the defaults.

However, there are times when you want to quickly send a message with a different sender ID. In such cases it does not make sense that you first have to go to the setting page to change the sender ID first, then come back to this send SMS page to send your SMS, then go back again to the settings page to restore the default sender ID.
This surely gives your plugin a poor user experience.
Please take a closer look into this especially for those who pay for this plugin.

**Comment by mostafasoufi** [comment]
Can be convincing.

Your merge approved.

Thank you.
