### ISSUE TITLE
Add new Gateway

### ISSUE THREAD

**Issue by marwanzak** [veronalabs/wp-sms#3]
Hi,
How to add our sms gateway?

**Comment by mostafasoufi** [comment]
Hello, please [click here](http://wp-sms.ir/gateways/) for add bew gateway.

Regards

**Comment by alexlii1971** [comment]
Hello,

That file is crashed, please check the the screenshot, would you please updated it?

http://prntscr.com/lp8ert

**Comment by froger-me** [comment]
Link that works: https://wp-sms-pro.com/gateways/
