### ISSUE TITLE
WP REST API endpoints

### ISSUE THREAD

**Issue by mostafasoufi** [veronalabs/wp-sms#30]
**Authentication**
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

**Endpoints**
- [x] Get subscribers (Authenticate required)
- [x] Add a new subscriber
- [x] Send SMS (Authenticate required)
- [x] Get credit (Authenticate required)

**Comment by MHitMaN** [comment]
Done.

**Comment by mostafasoufi** [comment]
👍
