### ISSUE TITLE
Disable the SMS subscriber assets in front

### ISSUE THREAD

**Issue by mostafasoufi** [veronalabs/wp-sms#45]
Should be available in the Style tab.

**Comment by MHitMaN** [comment]
Added option for this as we needed.
![2018-11-28_11-48-59](https://user-images.githubusercontent.com/20977558/49138199-d5125500-f303-11e8-8cf0-46f07bc7802f.png)

**Comment by mostafasoufi** [comment]
![screenshot-localhost-2018 11 28-16-27-23](https://user-images.githubusercontent.com/701520/49153321-aa87c280-f32a-11e8-886c-3ae31e9f9234.png)

It's better the activation should be hidden with hardcode.

**Comment by MHitMaN** [comment]
Activation is hidden now if the style disabled.
