### ISSUE TITLE
Status and response for outbox table

### ISSUE THREAD

**Issue by mostafasoufi** [veronalabs/wp-sms#46]
Please consider a database upgrader class for the plugin.

https://wordpress.stackexchange.com/questions/144870/wordpress-update-plugin-hook-action-since-3-9
https://wordpress.stackexchange.com/questions/25910/uninstall-activate-deactivate-a-plugin-typical-features-how-to/
https://stackoverflow.com/questions/40823796/updating-wordpress-plugin-database

**Comment by MHitMaN** [comment]
This feature added successfully with upgrade.php for tables but only for Hostiran Gateway, Please consider it, we need to apply this feature on all of the Gateways that we have.

**Comment by MHitMaN** [comment]
All Gateways now support Status and response on logs.
