### ISSUE TITLE
Send SMS to the Author of the post

### ISSUE THREAD

**Issue by MHitMaN** [veronalabs/wp-sms#56]
Add tiny URL Support For the publisher-author of posts.

The feature must be like this image :
![tiny-url](https://user-images.githubusercontent.com/20977558/50372189-d838f200-05de-11e9-8623-3389d0a2956c.png)

**Comment by MHitMaN** [comment]
Done.

**Comment by MHitMaN** [comment]
Fully tested and working well.

**Comment by ibraheemhsn** [comment]
such a quick action, thank you.
can't wait until see this in the second release.
