### ISSUE TITLE
connect to my kannel gateway

### ISSUE THREAD

**Issue by abumregha** [veronalabs/wp-sms#57]
can I connect this plug in to a kannel gateway api?

**Comment by mostafasoufi** [comment]
It's possible.
https://stackoverflow.com/questions/4768541/php-function-to-send-sms-via-kannel

**Comment by abumregha** [comment]
> It's possible.
> https://stackoverflow.com/questions/4768541/php-function-to-send-sms-via-kannel

how exactly is this related to connecting wp-sms to kannel?

**Comment by mostafasoufi** [comment]
You should create a gateway class in the plugin for sending SMS.
