### ISSUE TITLE
Support mobile fields with International Telephone Input

### ISSUE THREAD

**Issue by mostafasoufi** [veronalabs/wp-sms#58]
Library
https://github.com/jackocnr/intl-tel-input

This feature should be affected to below fields.
- [x] `add_mobile_field` option.
- [x] `bp_mobile_field` option.
- [x] `wc_mobile_field` option.
- [x] `edd_mobile_field` option.
- [x] `job_mobile_field` option.
- [x] `wpsms-mobile` field SMS newsletter.
- [x] `login-wpsms-mobile` field.
- [x] `OTP-wpsms-mobile` field.

Please consider this option should be available in **Setting > Features**

**Comment by mostafasoufi** [comment]
Thank you so much.

**Comment by mostafasoufi** [comment]
https://github.com/veronalabs/wp-sms/commit/fe474570bac46fbff4cfaf3b0c9f83b5481a497a

**Comment by mostafasoufi** [comment]
Please do below changes

- [ ] Rename all the prefix option name. e.g. `intel_mobile` to `international_mobile`
- [ ] Use the `wp_sms_get_option()` for get option in template. https://github.com/veronalabs/wp-sms/commit/fe474570bac46fbff4cfaf3b0c9f83b5481a497a#diff-6521f2baca8569b81a6f08016fa9c812

**Comment by MHitMaN** [comment]
Done.

**Comment by mostafasoufi** [comment]
It seems the below options does not working, because I couldn't find any conditions in the plugin that used.

```
intel_mobile_only_countries
intel_mobile_preferred_countries
intel_mobile_auto_hide
intel_mobile_national_mode
intel_mobile_separate_dial_code
```

Please consider the prefix of above option should be changed. `intel_*` to `international_*`

Thank you

**Comment by MHitMaN** [comment]
On Quform integration settings, changes dropped maybe, sorry for the conflict.
Fixed: https://github.com/veronalabs/wp-sms/commit/80b56fdfc42559d434d374fd3b4677e32d56733a

Done.

**Comment by mostafasoufi** [comment]
Thank you 👍
