### ISSUE TITLE
Improvement Send SMS meta box in post

### ISSUE THREAD

**Issue by mostafasoufi** [veronalabs/wp-sms#60]
Should be like with Send SMS page.

**Comment by MHitMaN** [comment]
Done.
Images Attached :
Desktop:
![2019-01-14_13-01-09](https://user-images.githubusercontent.com/20977558/51104994-f3250d80-17fc-11e9-845b-f393d59dfb57.png)

Mobile:
![2019-01-14_12-59-24](https://user-images.githubusercontent.com/20977558/51104999-f7512b00-17fc-11e9-8f7c-0295860f54d2.png)

**Comment by mostafasoufi** [comment]
Great!
