### ISSUE TITLE
Sort/Filter and Easier Manage of Groups/Subscribers

### ISSUE THREAD

**Issue by theVasilis** [veronalabs/wp-sms#66]
@MHitMaN it would really enhance the functionality of the plugin if we could easier manage the leads.

Use filtering / sorting functions, as well as group / campaign management options.

Please check it out.

Thank you

**Comment by MHitMaN** [comment]
Hello @theVasilis,

We will consider this thank you for your report.
1) Bulk add to groups.
2) add the group_ID on the Import section.
