### ISSUE TITLE
System info page

### ISSUE THREAD

**Issue by mostafasoufi** [veronalabs/wp-sms#71]
Menu position: After Settings

Items:
- [x] Check multisite
- [x] WordPress Version
- [x] Language
- [x] Active Theme
- [x] ABSPATH
- [x] Remote Post status
- [x] WP_DEBUG
- [x] WordPress Active Plugins
- [x] PHP Version
- [x] cURL
- [x] fsockopen
- [x] SOAP Client

**Comment by MHitMaN** [comment]
Done, but needs your review on it.

**Comment by mostafasoufi** [comment]
Thank you.

It's better the admin menu hooks move to `class-wpsms-admin.php`

**Comment by MHitMaN** [comment]
Done.
