### ISSUE TITLE
Problem Always show admin-bar.css

### ISSUE THREAD

**Issue by mehrshaddarzi** [veronalabs/wp-sms#97]
use `is_admin_bar_showing()` function for check admin bar is showing before render Css file.
@mostafasoufi 
@alifallahrn 

https://github.com/veronalabs/wp-sms/blob/75f919f7106206473ddac9c49d96438243dff03a/includes/class-front.php#L28

**Comment by mostafasoufi** [comment]
Thanks for the reporting, we'll do that.

**Comment by MHitMaN** [comment]
Done.
@mostafasoufi
