### ISSUE TITLE
Problem name Of Script in Hook

### ISSUE THREAD

**Issue by mehrshaddarzi** [veronalabs/wp-sms#98]
Please Add Prefix to prevent conflict another plugin , change `ajax-script` to `wp-sms-ajax-script`.
@mostafasoufi 
@alifallahrn 

https://github.com/veronalabs/wp-sms/blob/5861829dbd5cb629e6a72c3f4857034344443a9e/includes/class-wpsms-newsletter.php#L29

**Comment by MHitMaN** [comment]
Done.
@mostafasoufi
